### ISSUE TITLE
Interface Design을 수정

### ISSUE THREAD

**Issue by Tsujiku** [Tsujiku/personal-assistant#1]
계산기 쪽에서 좀 더 의미있는 변수를 사용하기 위해 디자인 문서(InterfaceDesign .doc)의 변수의 이름을 수정하였습니다. 문서 계산기 기능 항목에서 add, multiply, subtract, divide 함수의 매개변수 number1, number2 이름을 firstTerm과 secondTerm으로 수정하였으니 확인 바랍니다.

-디자인 문서 수정본: [Interface Design.pdf](https://github.com/Tsujiku/personal-assistant/files/1523584/Interface.Design.pdf)

**Comment by Hyenni** [comment]
문서 첨부는 확인 못했으나, 
fetch한 결과 매개변수의 변수명이 firstTerm, secondTerm으로 변경됐음을 확인하였습니다.

**Comment by chanyipk** [comment]
문서 첨부가 확인 되었습니다.
