### ISSUE TITLE
Issue Tracker 보고서 질문

### ISSUE THREAD

**Issue by Hyenni** [Tsujiku/personal-assistant#10]
보고서 쓸 때, 각각 기능별로 
• Purpose: for what reason did you use this functionality?
• Details of commands: what did you do in detail?
• Results: what did you obtain by using the functionality?
이러한 포맷으로 작성을 해야하는데 

create issue는 각자 올린 issue 3개에 대해 각각의 목적이 뭐고, 어떻게 했으며, 어떤 결과를 가져왔는지 작성하면 되는데
예를 들어 
close issue라고 한다면, 해결됐기 때문에 close를 한 건데 이에 대한 목적과 무엇을 했으며 어떤 것을 얻었는지는 어떻게 무엇을 써야할까요?
create issue한 것을 모두 해결해 다 close 했다면, close한 화면을 다 올리되 자세한 설명은 크게 하나로 묶어서 작성해도 되는걸까요?

제 질문이 이해됐을지 모르겠네요ㅠㅠㅠㅠ comment 기다리겠습니다

**Comment by Tsujiku** [comment]
이슈가 완료됐다고 판단한 근거가 close issue의 목적이 될 수 있을것 같습니다.
예를 들어, issue label이 "bug"였다면 --> "debug" 과정을 작성하여 문제가 어떻게 해결된 건지 작성합니다. 물론 캡쳐 화면에 내용이 담겨있지만, 그 내용을 요약해서 쓰면 될 것 같습니다.
issue label이 만약 "reference"였다면 --> 모두가 다 답글을 달아 확인했다 정도를 작성할 수 있습니다.
추가로, close의 경우 create랑 같이 연계해서 써도 문제 없을 것 같습니다!

**Comment by Hyenni** [comment]
자세한 설명 감사합니다. 
많은 도움이 됐습니다 :-)
