### ISSUE TITLE
Accountbook 파일 저장 문제 (ArrayList)

### ISSUE THREAD

**Issue by Hyenni** [Tsujiku/personal-assistant#13]
가계부에서 사용자 입력으로 date, item, price를 입력 받는데 각각 띄어쓰기로 구분이 가능합니다.
문제는 한 레코드(date, item, price)를 입력받고 줄바꿈 적용이 안됩니다.
 
memo 같은 경우는 하나의 문자열만 받기 때문에 구현할 시 사용자가 입력하면 바로 개행문자(\r\n)를 넣어 줄바꿈이 가능하였으나,
accountbook은 세 개의 column을 받기 때문에 사이사이에는 띄어쓰기를, 한 레코드를 입력받고 나서는 개행문자를 처리해야 하는 애로사항이 발생하였습니다.

완벽하지 않지만 지금까지 구현한 작업을 push할 테니 코드를 살펴보고,
어떻게 해결하면 좋을지 다양한 의견 부탁드립니다!

**Comment by chanyipk** [comment]
ArrayList에 add할 때, 입력한 가격, 날짜, 제품명을 각각 add하는 것이 아니라 이 세 개를 String으로 하나로 묶은 후 ArrayList에 합치셔야 정상적으로 잘 입력됩니다. 그리고 confirm하는 과적에서 allcontents의 값을 ""로 해야 됩니다.

**Comment by Hyenni** [comment]
아!!!!!! 정말 감사합니다.
알려주신대로 코드 수정했더니 accountbook.txt 파일에 레코드 별로 깔끔하게 upload 됨을 확인하였습니다 . 
아래의 사진처럼 사용자의 입력을 이러한 방식으로 파일에 저장하니 참고 바랍니다.
<img width="260" alt="ex" src="https://user-images.githubusercontent.com/33708512/33522708-84abf0fa-d836-11e7-8ffd-01b959f87eb0.PNG">
