### ISSUE TITLE
.gitignore 파일 생성하기 

### ISSUE THREAD

**Issue by Hyenni** [Tsujiku/personal-assistant#3]
git에  push할 때 .metadata 폴더, RemoteSystemTempFiles 폴더, .recommenders 폴더를 무시한 채 
온전히 소스파일만 올라갈수 있게 환경 구축을 변경해주시기 바랍니다.

**Comment by chanyipk** [comment]
환경 구축하는 방법에 대해 순차적으로 알려주시면 감사하겠습니다.

**Comment by Hyenni** [comment]
vi .gitignore 명령어를 친 뒤, .metadata/*, .recommenders/* 의 식으로 입력하여 gitignore 파일을 생성하면
됩니다. 
자세한 건 제가 commit 해서 올린 gitignore 파일을 참고하면 더 이해가 될 것 같습니다.

**Comment by chanyipk** [comment]
해당 방법 말고 push할 당시 .java 만을 업로드 하여도 문제가 생기지 않았습니다.
gitignore 파일을 만들지 않아도 괜찮을 것 같습니다.

**Comment by Tsujiku** [comment]
제가 처음 push할 때 이클립스 환경까지 올렸었습니다.. 죄송해요 ㅠㅠ 
ignore은 프로젝트 폴더 .metadata/ 하위항목을 update하지 않도록 하는 데 도움이 되는 것 같아요!

**Comment by Hyenni** [comment]
chanyipk ) 의견 감사합니다. 그렇다면 add, push를 할 시 해당 .java 파일만 올라갈 수 있도록 해요!
Tsujiku ) 아닙니다. 처음에 어떤게 문제인지 몰랐는데 문제가 생겨 해결하면서 원인을 파악할 수 있었습니다^^ 이를 해결하기 위해서 .java파일만 업로드 해주세요!!
