### ISSUE TITLE
AccountBook.class - non-functional requirement 추가 사항

### ISSUE THREAD

**Issue by chanyipk** [Tsujiku/personal-assistant#4]
AccountBook 기능 사용 시 사용자로부터 입력을 받을 때, 사용자는 띄어쓰기를 하면 안된다는 제약사항이 추가되었으므로 해당 기능 구현자는 이를 숙지하시고 개발에 임하시길 바랍니다.

**Comment by Hyenni** [comment]
사용자 입력 부분은 제약사항을 반영하여 코드 구현하였습니다.
코드 점검한 뒤 push하겠습니다.
