### ISSUE TITLE
가장 최근 수정사항 반영 문제

### ISSUE THREAD

**Issue by github9604** [Tsujiku/personal-assistant#5]
![default](https://user-images.githubusercontent.com/32297235/33333706-e28ce844-d4aa-11e7-83c3-ffaf56b0022c.JPG)
![default](https://user-images.githubusercontent.com/32297235/33333712-e7208c94-d4aa-11e7-9261-3476802f1fc3.JPG)

fetch를 실행하고 나서 출력되는 내용을 확인해보면 github에서 수정된 내용을 잘 가져오는 것 같은데 eclipse에서 file을 열었을 때는 아무런 변화가 없더라구요. 혹시 또 clone을 해야하는건지 다른 팀원들도 fetch 명령어로 수정 내용 반영하신거면 제가 변경된 내용이 다른 파일로 저장된건 아닌지 다시 한 번 찾아보겠습니다.

**Comment by Hyenni** [comment]
fetch 한 후 merge 까지 하였나요??

**Comment by github9604** [comment]
Workspace 변경하고 새로 project file open 하니까 해결됐어요!

**Comment by Tsujiku** [comment]
자주 이런 일이 일어난다면, 아래의 링크 방법을 사용하는 것도 좋을것 같습니다!
[이클립스와 git연동](http://itmir.tistory.com/461)
