### ISSUE TITLE
branch에 대해서

### ISSUE THREAD

**Issue by chanyipk** [Tsujiku/personal-assistant#7]
각자 branch를 만든 후 작업을 하는 것으로 알고 있는데 그러면 git에 업로드할 때 branch가 생겨야하지 않나요?
저희 프로젝트에는 master밖에 branch가 없어 의문이 들어서 말입니다.

**Comment by Tsujiku** [comment]
교수님께 여쭤본 결과, 두 가지 방법으로 push(git에 업로드)할 수 있습니다.

1) branch를 생성한 상태로 업로드할 경우, origin master에도 branch가 생깁니다. 주로 대형 프로젝트에 사용되고, 이슈에 맞춰 여러개의 branch가 생성된 형태로 프로젝트 진행이 가능합니다! chanyipk님이 말씀하신 내용이 이 방법에 해당하는 것 같고, 이렇게 branch가 만들어져서 작업해도 됩니다!

2) Local PC에서 생성한 branch를 master에서 merge한 후 commit된 내용을 git에 업로드할 수 있습니다.
이렇게 하게 되면 각자가 origin master에는 일렬로, 각자 작업한 내용이 업로드되는 것이죠!

저희는 저번에 일단 2번 방식으로 진행하기로 협의했던 것 같습니다. 각자 맡은 바에 따라 issueCalculator, issueMemo, issueAccountBook 등으로 로컬 브렌치에서 형성해서 merge후 commit하는 것으로 알고 있습니다. 그러나 서로 공통으로 겹치는 작업이 크지 않기 때문에 1번 방식으로 branch 생성해서 업로드하셔도 좋을 것 같아요.

**Comment by Hyenni** [comment]
아!!!!! 저도 이게 궁금했습니다. 
그렇다면 2번 방법으로 진행하는 경우, 지금 우리 network 그림처럼 master branch(검은색)로 commit이 일어나는 것 맞죠?
