### ISSUE TITLE
메모기능에 사용된 ArrayList에 관해서

### ISSUE THREAD

**Issue by chanyipk** [Tsujiku/personal-assistant#8]
메모 기능에서 구현에 사용된 ArrayList가 기존에 작성한 문서와는 다르게 구현되었습니다.

문서에서는 ArrayList에 index 번호와 함께 내용을 저장하기 위해서 이차원 구조를 가져야 하는 것이라 생각했는데 구현 당시에는 그럴 필요가 없었습니다.

구현한 방식이 더 단순하기는 하나 우리의 방식은 waterfall과 비슷하기 때문에 문서와 동일한 방법으로 가야하는 것인지 의견을 구하고 싶습니다.

**Comment by Tsujiku** [comment]
저는 구현하기 좋은 쪽으로 변경해도 괜찮다고 생각합니다. Constraints가 아닌 functionality는 개발자 권한이라고 생각합니다. 디자인대로 완벽히 반영하기 어려우니까요! =)

**Comment by Hyenni** [comment]
저도 위와 같은 의견입니다.  
더 단순한 방식으로 변경해도 괜찮다고 생각합니다.
