### ISSUE TITLE
Calculator 사용자 입력 대응 문제

### ISSUE THREAD

**Issue by Tsujiku** [Tsujiku/personal-assistant#9]
Calculator 기능 지금까지 구현된 것을 사용해 보시면 알겠지만, Calculator 1번의 Arithmetic Operation(산술연산) 기능에 다음과 같은 문제점이 있습니다.

사용자가 계산하고자하는 식을 입력받을 때 현재 공백으로 각 숫자와 기호를 구분하게 해 두었습니다.
그래서 현재 프로그램에서는 입력은 꼭 (숫자)(공백)(산술기호)(공백)(숫자) 순으로 입력해야 합니다. ex) Enter formula to calculate: 1 + 2
계산을 입력할 때 위와 같이 형식을 꼭 맞춰주어야 제대로 산술연산을 할 수 있게되는데요.
이에 대해 아래와 같은 입력들도 대응해야 될것 같아요!

//TODO 사용자 입력식 대응하기
유형1. 부호를 일일히 입력하는 경우 ex) +2+3
유형2. 잘못 식을 입력한 경우 ex) 1 ++ 2
유형3. 공백이 입력되지 않은 경우 ex) 1+2

입력식 대응에는 입력할 때 위와 같은 여러 유형을 해결할 수 있는 방법으로 코드를 수정하거나, 사용자에게 입력 포맷을 알려주는 방법이 있을 것 같은데 여러분의 생각은 어떠신가요? 일단 제가 코드를 수정해 나가고 있긴 합니다! 자유로이 의견을 말씀해 주시면 감사하겠습니다! =)

**Comment by Hyenni** [comment]
사용자에게 입력 포맷을 알려주되, 간단한 실수(?) 같은 것은 예외처리 해야하지 않을까요? 
예를들어 유형3처럼 공백을 입력하지 않았을 때는 사용자가 아예 잘못된 수식을 입력한 것이 아니라 누구라도 이해할 수 있는 수식이니까요! 
공백을 처리하는 예외처리정도는 구현이 됐으면 좋겠습니다!

**Comment by github9604** [comment]
구글에 검색해본 결과 유형 3경우에는 인식을 하더라구요! 저희도 공백이 입력되는 경우, 입력되지 않는 경우 두 가지를 고려하면 될 것 같습니다 :-)

**Comment by Tsujiku** [comment]
유형 1,2,3 등 모두 함께 해결하였습니다. 테스트 부탁드립니다!

**Comment by github9604** [comment]
![1](https://user-images.githubusercontent.com/32297235/33552437-352c81fe-d938-11e7-892d-766a9432a5c6.JPG)
코드를 실행하니 이러한 오류를 발견했습니다! 오류 메세지와 함께 the answer is 이라는 문장이 함께 출력됩니다.

**Comment by Tsujiku** [comment]
github9604님 감사합니다!! "="표시에 대한 생각을 못하였는데, 해당 내용 반영하겠습니다.
